### PR TITLE
add nullable instance

### PR DESCRIPTION
**Pull request by justinwoo**

### CODE REVIEW

**Comment by jacereda** [comment]
Looks good.

**Comment by justinwoo** [comment]
Updated this to actually require that the field be `null` and not just `undefined`, throwing a type mismatch error of `Nullable a` `Undefined` in that case.

**Comment by jacereda** [comment]
Looks good, but shouldn't -foreign provide `readNullable`?

**Comment by justinwoo** [comment]
Nullable is from https://pursuit.purescript.org/packages/purescript-nullable/3.0.0/docs/Data.Nullable and it doesn't really come with anything though

**Pull request merged**
